name: Docker CD Database Pipeline

on:
  push:

    paths:
      - '.github/workflows/deployDB.yml'
      - 'deliverables/yres_scheduler/yres_scheduler_database/yres_schema.sql'

jobs:
  transfer-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transfer code to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: . 
          target: /home/ubuntu/yres

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/yres/deliverables/yres_scheduler/yres_scheduler_database
            sudo docker-compose down --volumes || true
            sudo docker-compose up -d
  # build-test-deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Login to Docker hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and Push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: deliverables/yres_scheduler/yres_scheduler_database
  #         push: true
  #         tags: erickarp/postgres:${{ github.sha }}

  #     - name: Deploy to EC2 instance 
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: ${{ secrets.EC2_USERNAME }}
  #         key: ${{ secrets.EC2_PRIVATE_KEY }}
  #         working-directory: deliverables/yres_scheduler/yres_scheduler_database
  #         script: |
  #           sudo docker stop postgres || true
  #           sudo docker rm postgres || true
  #           sudo docker pull ${{ secrets.DOCKER_USERNAME }}/postgres:${{ github.sha }}
  #           sudo docker run -d --name postgres -p 3001:5432 ${{ secrets.DOCKER_USERNAME }}/postgres:${{ github.sha }}
