
name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install
      working-directory: deliverables/yres_scheduler/yres_scheduler_backend

    - name: Run Node.js Server
      run: |
        node server.js &
          sleep 5  # Allow some time for the server to start
        # kill -2 $(jobs -p)  # Send SIGINT to the background jobs
      working-directory: deliverables/yres_scheduler/yres_scheduler_backend

    - name: Run all the backend tests
      run: npm test
      working-directory: deliverables/yres_scheduler/yres_scheduler_backend

